### ISSUE TITLE
Arduino-Based Attack Vector - [Errno 2] No such file or directory: '/usr/share/set/config/set_config'

### ISSUE THREAD

**Issue by aj1322001** [trustedsec/social-engineer-toolkit#163]
version 6.5.6 following from startup..

1
6
1
y
ip entry
port 443
1

set:payloads> Enter the number for the payload [meterpreter_reverse_tcp]:1
[*] Prepping pyInjector for delivery..

[!] Something went wrong, printing the error: [Errno 2] No such file or directory: '/usr/share/set/config/set_config'

**Comment by trustedsec** [comment]
Fixed this in 6.5.7 - thanks for the report!

**Comment by MAHDI00032** [comment]
Not fixed

[!] Something went wrong, printing the error: [Errno 2] No such file or directory: '/etc/setoolkit/set.config'

Im using termux
